name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Deploy to gh-pages branch
        run: |
          # Configure git
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Create a temporary directory for the build
          mkdir -p build
          
          # Copy only the necessary files for the static site
          cp -r index.html css js build/
          cp .nojekyll build/
          
          # Create a simple README for the gh-pages branch
          echo "# DAISYS Speech Editing Demo" > build/README.md
          echo "" >> build/README.md
          echo "This branch contains the deployed static site." >> build/README.md
          echo "" >> build/README.md
          echo "Visit the demo at: https://\${{ github.repository_owner }}.github.io/\${{ github.event.repository.name }}/" >> build/README.md
          echo "" >> build/README.md
          echo "Configure with URL parameters:" >> build/README.md
          echo "- Mock mode: ?mock=true" >> build/README.md
          echo "- Custom API: ?api_url=YOUR_API&auth_url=YOUR_AUTH" >> build/README.md
          
          # Checkout gh-pages branch (create if doesn't exist)
          git checkout -B gh-pages
          
          # Remove all existing files
          git rm -rf . || true
          
          # Copy build files to root
          cp -r build/* .
          rm -rf build
          
          # Add all files
          git add -A
          
          # Commit and push
          git commit -m "Deploy to GitHub Pages: ${{ github.sha }}" || echo "No changes to commit"
          git push -f origin gh-pages